// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEb0EiSYfoHB2yJRWvyPBAg8kao1Af-WE',
    appId: '1:164321630854:web:1f39fda7ead170d9128f07',
    messagingSenderId: '164321630854',
    projectId: 'calculator-6e832',
    authDomain: 'calculator-6e832.firebaseapp.com',
    storageBucket: 'calculator-6e832.appspot.com',
    measurementId: 'G-4GGDR69H3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGnMlgwyv9XDV4srns0NUmXcN3y7kBpw',
    appId: '1:164321630854:android:b763ae35d37074c2128f07',
    messagingSenderId: '164321630854',
    projectId: 'calculator-6e832',
    storageBucket: 'calculator-6e832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXUSJMh0hJOBvLABVWmVcRyFsXw6iTZbY',
    appId: '1:164321630854:ios:66380437b1e799ab128f07',
    messagingSenderId: '164321630854',
    projectId: 'calculator-6e832',
    storageBucket: 'calculator-6e832.appspot.com',
    iosClientId: '164321630854-d526qik4rssphofdvkn37h58jv9nl76h.apps.googleusercontent.com',
    iosBundleId: 'com.example.protoCalculator',
  );
}
