name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  cloud_firestore: ^3.1.15
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get: ^4.6.3
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  sign_in_with_apple: ^3.3.0
  streaming_shared_preferences: ^2.0.0
  uuid: ^3.0.6
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
